# Generated by Django 4.1 on 2022-09-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='거래 금액')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tr_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transaction.transactioninfo')),
                ('is_transferred', models.BooleanField(default=False, verbose_name='거래 여부')),
            ],
        ),
    ]
