# Generated by Django 4.1 on 2022-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='계좌명')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='계좌번호')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='투자 원금')),
                ('stock_firm', models.CharField(choices=[('디셈버증권', '디셈버증권'), ('베스트투자', '베스트투자'), ('핀트투자증권', '핀트투자증권')], max_length=20, verbose_name='증권사')),
            ],
        ),
    ]
