# Generated by Django 4.1 on 2022-09-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='계좌번호'),
        ),
    ]
